server:
  port: 8086
 
  
spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/ratingservice
   username: postgres
   password: root
   
   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.PostgreSQL94Dialect
  application:
    name: RATING-SERVICE 
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  
    
      
    
    